version: "3"
services:

  db:
    image: postgres:9.6
    restart: always
    environment:
      POSTGRES_PASSWORD: cmais
      POSTGRES_DB: cmais
    ports:
      - 5435:5432
    volumes:
      - ./postgres-data:/bitnami/postgresql/data
